/*
 * ft.c
 * 
 * Copyright 2017 shad0w <x32@parrot>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
int main()
{
	
    FILE *fpa, *fpb;
    char cha;
    int nof=0;
    
    
    
    /*first file generated by the api*/
    fpa = fopen("raw.txt","r");
    if(fpa == NULL)
    {	
		printf("oOps2:: Sorry can't open the file...");
		exit(1);
	}
		
	
	
		
	/*second file to copy on*/	
	fpb = fopen("mod.txt","w+");	
    if(fpb == NULL)
    {	
		printf("oOps3:: Sorry can't open the file...");
		exit(1);
		
	}
	
	
	
	
	while(nof<=4)
	{
		cha = fgetc(fpa);
		if(cha==EOF)
		{
			break;
		}
		else
		{
			fputc(cha,fpb);
		}
		if(cha=='.')
		{
			nof++;
		}
	}
	
	
	
	/*closing both files*/
	fclose(fpa);
	fclose(fpb);
	
	system("printf ':: ' && cat mod.txt");
	system("festival --tts mod.txt");

return 0;
}


